# -*- coding: utf-8 -*-
"""extrator.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gGq93WHzpqNxwQNdUco3ftLrauNY0DOs
"""

!pip install pymupdf
import fitz

!pip install python-docx

import os

# Listar o conteúdo do Meu Drive para verificar se a pasta esta ou nao la
caminho_drive = '/content/drive/My Drive'
for pasta in os.listdir(caminho_drive):
    print(pasta)

import os
import fitz  # Pymupdf
from docx import Document

# Função para extrair texto do PDF
def extrair_texto_pdf(caminho_pdf):
    doc = fitz.open(caminho_pdf)
    texto_completo = ""
    for pagina in doc:
        texto_completo += pagina.get_text() + "\n"
    return texto_completo

# Função para salvar o texto em um arquivo Word
def salvar_em_word(texto, caminho_arquivo):
    doc = Document()
    doc.add_paragraph(texto)
    doc.save(caminho_arquivo)

def processar_pdfs(pasta_pdf):
    for arquivo in os.listdir(pasta_pdf):
      #vamos ignorar tudo que nao eh pdf (queremos extrair os dados do pdf)
        if arquivo.endswith('.pdf'):
          # Isso é necessário porque o os.listdir() retorna apenas o nome do arquivo, tem separador automatico "/"
            caminho_pdf = os.path.join(pasta_pdf, arquivo)
            texto_extraido = extrair_texto_pdf(caminho_pdf)
            #mantem o mesmo nome de arquivo so que com outra extensão
            nome_docx = arquivo.replace('.pdf', '.docx')
            caminho_docx = os.path.join(pasta_pdf, nome_docx)  # Salvar na mesma pasta
            salvar_em_word(texto_extraido, caminho_docx)
            print(f"Texto extraído e salvo em {caminho_docx}")

# especifico do colab, tem que montar um drive se estiver usadno arquivos de la
from google.colab import drive
drive.mount('/content/drive')

# aqui entra a pasta onde estao os arquivos
pasta_pdf = 'caminho'
processar_pdfs(pasta_pdf)

# isso para conferencia dos arquivos da pasta
print("Arquivos .docx na pasta:")
for arquivo in os.listdir(pasta_pdf):
    if arquivo.endswith('.docx'):
        print(arquivo)